# On commit this workflow will run tests

name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Use Node.js  12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci

      - name: build static production files
        run: npm run build

      - name: run unit test
        run: npm run ci:test
        env:
          CI: true
